# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MD_App\UI\app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6.QtCore import pyqtSignal as Signal, Qt, QSize, QRect, QMetaObject
from PyQt6.QtGui import QImage, QPixmap
from PyQt6.QtWidgets import (QWidget, QLabel, QSlider, QPushButton,
    QGroupBox, QComboBox, QTabWidget, QProgressBar, QLineEdit, QSizePolicy,
    QApplication, QDoubleSpinBox, QSpinBox, QListWidget, QFileDialog)


class Ui_Form(object):
    speed:int = 150
    # motor_speed_signal and speed are defined in MainApp (the actual QObject/QWidget subclass)

    def motor_speed_update(self, speed, isSliderMove:bool):
        if isSliderMove:
            self.moto_stat_slider.setValue(speed)
        self.moto_stat_label.setText(f"Power : {speed}")
        self.speed = speed

    def motor_speed_slider_valuechange(self, value):
        self.motor_speed_signal.emit(value, False)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1450, 1000)
        # 타이틀바 최대화 버튼 활성화: Fixed SizePolicy 제거, MaximumSize 제한 없애
        Form.setMinimumSize(QSize(1450, 1000))
        self.cam_label = QLabel(Form)
        self.cam_label.setGeometry(QRect(390, 40, 640, 480))
        self.cam_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.cam_label.setObjectName("cam_label")
        # self.cam_label.setStyleSheet("background-color: black; border: 2px solid gray;")
        self.cam_pan_slider = QSlider(Form)
        self.cam_pan_slider.setGeometry(QRect(390, 530, 640, 40))
        self.cam_pan_slider.setOrientation(Qt.Orientation.Horizontal)
        self.cam_pan_slider.setObjectName("cam_pan_slider")
        self.cam_tilt_slider = QSlider(Form)
        self.cam_tilt_slider.setGeometry(QRect(1080, 40, 50, 480))
        self.cam_tilt_slider.setOrientation(Qt.Orientation.Vertical)
        self.cam_tilt_slider.setObjectName("cam_tilt_slider")
        self.distance_label = QLabel(Form)
        self.distance_label.setGeometry(QRect(950, 585, 100, 40))
        self.distance_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.distance_label.setObjectName("distance_label")
        self.moto_cntrl = QWidget(Form)
        self.moto_cntrl.setGeometry(QRect(120, 230, 320, 280))
        self.moto_cntrl.setObjectName("moto_cntrl")
        
        self.moto_btn_frontleft = QPushButton(self.moto_cntrl)
        self.moto_btn_frontleft.setGeometry(QRect(0, 70, 80, 70))
        self.moto_btn_frontleft.setObjectName("moto_btn_frontleft")
        
        self.moto_btn_frontright = QPushButton(self.moto_cntrl)
        self.moto_btn_frontright.setGeometry(QRect(160, 70, 80, 70))
        self.moto_btn_frontright.setObjectName("moto_btn_frontright")
        
        self.moto_btn_front = QPushButton(self.moto_cntrl)
        self.moto_btn_front.setGeometry(QRect(80, 70, 80, 70))
        self.moto_btn_front.setObjectName("moto_btn_front")
        self.moto_btn_left = QPushButton(self.moto_cntrl)
        self.moto_btn_left.setGeometry(QRect(0, 140, 80, 70))
        self.moto_btn_left.setObjectName("moto_btn_left")
        self.moto_btn_right = QPushButton(self.moto_cntrl)
        self.moto_btn_right.setGeometry(QRect(160, 140, 80, 70))
        self.moto_btn_right.setObjectName("moto_btn_right")
        self.moto_btn_back = QPushButton(self.moto_cntrl)
        self.moto_btn_back.setGeometry(QRect(80, 210, 80, 70))
        self.moto_btn_back.setObjectName("moto_btn_back")
        
        self.moto_btn_backleft = QPushButton(self.moto_cntrl)
        self.moto_btn_backleft.setGeometry(QRect(0, 210, 80, 70))
        self.moto_btn_backleft.setObjectName("moto_btn_backleft")
        
        self.moto_btn_backright = QPushButton(self.moto_cntrl)
        self.moto_btn_backright.setGeometry(QRect(160, 210, 80, 70))
        self.moto_btn_backright.setObjectName("moto_btn_backright")
        
        self.moto_btn_rotate_right = QPushButton(self.moto_cntrl)
        self.moto_btn_rotate_right.setGeometry(QRect(0, 0, 80, 70))
        self.moto_btn_rotate_right.setObjectName("moto_btn_rotate_right")
        self.moto_btn_rotate_left = QPushButton(self.moto_cntrl)
        self.moto_btn_rotate_left.setGeometry(QRect(160, 0, 80, 70))
        self.moto_btn_rotate_left.setObjectName("moto_btn_rotate_left")
        self.robot_ip_label = QLabel(Form)
        self.robot_ip_label.setGeometry(QRect(570, 0, 150, 30))
        self.robot_ip_label.setObjectName("robot_ip_label")
        self.pushButton = QPushButton(Form)
        self.pushButton.setGeometry(QRect(850, 0, 100, 30))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QLineEdit(Form)
        self.lineEdit.setGeometry(QRect(650, 0, 150, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setGeometry(QRect(0, 0, 380, 220))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QRect(0, 15, 80, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QRect(100, 15, 80, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QRect(200, 15, 80, 50))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QRect(300, 15, 80, 50))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QRect(0, 75, 80, 50))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QRect(100, 75, 80, 50))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QRect(200, 75, 80, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QRect(300, 75, 80, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QLabel(self.groupBox)
        self.label.setGeometry(QRect(120, 130, 120, 20))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QRect(60, 150, 50, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_3 = QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QRect(180, 150, 50, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_4 = QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QRect(300, 150, 50, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pushButton_10 = QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QRect(150, 180, 75, 30))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setGeometry(QRect(0, 150, 55, 20))
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setGeometry(QRect(120, 150, 55, 20))
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setGeometry(QRect(240, 150, 55, 20))
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_11 = QPushButton(Form)
        self.pushButton_11.setGeometry(QRect(1040, 0, 121, 30))
        self.pushButton_11.setObjectName("pushButton_11")

        self.buzzer_btn = QPushButton(Form)
        self.buzzer_btn.setGeometry(QRect(1050, 533, 110, 30))
        self.buzzer_btn.setObjectName("buzzer_btn")
        self.buzzer_btn.setText("Toggle_Buzzer")

        self.sendgroup = QGroupBox(Form)
        self.sendgroup.setTitle("Connection Send")
        self.sendgroup.setGeometry(QRect(10, 565, 950, 50))
        self.sendgroup.setObjectName("sendgroup")
        self.sendlabel = QLineEdit(self.sendgroup)
        self.sendlabel.setReadOnly(True)
        self.sendlabel.setGeometry(QRect(5, 15, 930, 30))
        self.sendlabel.setObjectName("sendlabel")
        # self.sendlabel.setText(_translate("Form", "Send : "))

        # self.recvlabel = QtWidgets.QLineEdit(Form)
        # self.recvlabel.setReadOnly(True)
        # self.recvlabel.setGeometry(QtCore.QRect(1230, 40, 100, 480))
        # self.recvlabel.setObjectName("recvlabel")
        # self.recvlabel.setText(_translate("Form", "Recv : "))

        self.moto_status_group = QGroupBox(Form)
        self.moto_status_group.setTitle("Motor Status")
        self.moto_status_group.setGeometry(QRect(10, 230, 100, 330))
        self.moto_status_group.setObjectName("moto_status_group")
        self.moto_stat_slider = QSlider(self.moto_status_group)
        self.moto_stat_slider.setGeometry(QRect(10, 15, 80, 280))
        self.moto_stat_slider.setOrientation(Qt.Orientation.Vertical)
        self.moto_stat_slider.setRange(0, 255)
        self.moto_stat_slider.setValue(self.speed)
        self.moto_stat_slider.setObjectName("moto_stat_slider")
        self.moto_stat_label = QLabel(self.moto_status_group)
        self.moto_stat_label.setGeometry(QRect(10, 300, 80, 30))
        self.moto_stat_label.setObjectName("moto_stat_label")
        self.moto_stat_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # ── run_for 패널 ──────────────────────────────────────────
        from PyQt6.QtWidgets import QComboBox, QDoubleSpinBox, QSpinBox
        self.run_for_group = QGroupBox(Form)
        self.run_for_group.setTitle("Timed Run (run_for)")
        self.run_for_group.setGeometry(QRect(1180, 5, 260, 290))
        self.run_for_group.setObjectName("run_for_group")

        _lbl_dir = QLabel("Direction :", self.run_for_group)
        _lbl_dir.setGeometry(QRect(10, 30, 80, 25))

        self.run_for_dir_combo = QComboBox(self.run_for_group)
        self.run_for_dir_combo.setObjectName("run_for_dir_combo")
        self.run_for_dir_combo.setGeometry(QRect(95, 30, 150, 25))
        for label in ["전진 (Forward)", "후진 (Backward)",
                      "좌측 (Left)", "우측 (Right)",
                      "대각 전좌 (FrontLeft)", "대각 전우 (FrontRight)",
                      "대각 후좌 (BackLeft)", "대각 후우 (BackRight)",
                      "좌회전 (RotateL)", "우회전 (RotateR)"]:
            self.run_for_dir_combo.addItem(label)

        _lbl_spd = QLabel("Speed :", self.run_for_group)
        _lbl_spd.setGeometry(QRect(10, 75, 80, 25))

        self.run_for_speed_spin = QSpinBox(self.run_for_group)
        self.run_for_speed_spin.setObjectName("run_for_speed_spin")
        self.run_for_speed_spin.setGeometry(QRect(95, 75, 150, 25))
        self.run_for_speed_spin.setRange(0, 255)
        self.run_for_speed_spin.setValue(150)
        self.run_for_speed_spin.setSuffix("  (0~255)")

        _lbl_sec = QLabel("Seconds :", self.run_for_group)
        _lbl_sec.setGeometry(QRect(10, 120, 80, 25))

        self.run_for_sec_spin = QDoubleSpinBox(self.run_for_group)
        self.run_for_sec_spin.setObjectName("run_for_sec_spin")
        self.run_for_sec_spin.setGeometry(QRect(95, 120, 150, 25))
        self.run_for_sec_spin.setRange(0.1, 60.0)
        self.run_for_sec_spin.setSingleStep(0.1)
        self.run_for_sec_spin.setDecimals(1)
        self.run_for_sec_spin.setValue(2.0)
        self.run_for_sec_spin.setSuffix(" s")

        self.run_for_btn = QPushButton("▶ Run", self.run_for_group)
        self.run_for_btn.setObjectName("run_for_btn")
        self.run_for_btn.setGeometry(QRect(10, 165, 235, 40))

        self.run_for_status_label = QLabel("대기 중", self.run_for_group)
        self.run_for_status_label.setObjectName("run_for_status_label")
        self.run_for_status_label.setGeometry(QRect(10, 215, 235, 25))
        self.run_for_status_label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # 진행 프로그레스바
        from PyQt6.QtWidgets import QProgressBar
        self.run_for_progress = QProgressBar(self.run_for_group)
        self.run_for_progress.setObjectName("run_for_progress")
        self.run_for_progress.setGeometry(QRect(10, 250, 235, 20))
        self.run_for_progress.setRange(0, 100)
        self.run_for_progress.setValue(0)
        self.run_for_progress.setTextVisible(False)

        # ── Motor Control 그룹 ────────────────────────────────────
        self.moto_ctrl_group = QGroupBox(Form)
        self.moto_ctrl_group.setTitle("Motor Control")
        self.moto_ctrl_group.setGeometry(QRect(1180, 300, 250, 240))
        self.moto_ctrl_group.setObjectName("moto_ctrl_group")

        self.moto_ctnl1_up_btn = QPushButton("LF↑", parent=self.moto_ctrl_group)
        self.moto_ctnl1_up_btn.setGeometry(QRect(10, 20, 80, 40))
        self.moto_ctnl1_up_btn.setObjectName("moto_ctnl1_up_btn")
        self.moto_ctnl1_down_btn = QPushButton("LF↓", parent=self.moto_ctrl_group)
        self.moto_ctnl1_down_btn.setGeometry(QRect(10, 70, 80, 40))
        self.moto_ctnl1_down_btn.setObjectName("moto_ctnl1_down_btn")

        self.moto_ctnl2_up_btn = QPushButton("LB↑", parent=self.moto_ctrl_group)
        self.moto_ctnl2_up_btn.setGeometry(QRect(10, 140, 80, 40))
        self.moto_ctnl2_up_btn.setObjectName("moto_ctnl2_up_btn")
        self.moto_ctnl2_down_btn = QPushButton("LB↓", parent=self.moto_ctrl_group)
        self.moto_ctnl2_down_btn.setGeometry(QRect(10, 190, 80, 40))
        self.moto_ctnl2_down_btn.setObjectName("moto_ctnl2_down_btn")

        self.moto_ctnl3_up_btn = QPushButton("RF↑", parent=self.moto_ctrl_group)
        self.moto_ctnl3_up_btn.setGeometry(QRect(160, 20, 80, 40))
        self.moto_ctnl3_up_btn.setObjectName("moto_ctnl3_up_btn")
        self.moto_ctnl3_down_btn = QPushButton("RF↓", parent=self.moto_ctrl_group)
        self.moto_ctnl3_down_btn.setGeometry(QRect(160, 70, 80, 40))
        self.moto_ctnl3_down_btn.setObjectName("moto_ctnl3_down_btn")

        self.moto_ctnl4_up_btn = QPushButton("RB↑", parent=self.moto_ctrl_group)
        self.moto_ctnl4_up_btn.setGeometry(QRect(160, 140, 80, 40))
        self.moto_ctnl4_up_btn.setObjectName("moto_ctnl4_up_btn")
        self.moto_ctnl4_down_btn = QPushButton("RB↓", parent=self.moto_ctrl_group)
        self.moto_ctnl4_down_btn.setGeometry(QRect(160, 190, 80, 40))
        self.moto_ctnl4_down_btn.setObjectName("moto_ctnl4_down_btn")

        # ── 거리 + 방향 제어 패널 ─────────────────────────────────────────
        self.dist_dir_group = QGroupBox(Form)
        self.dist_dir_group.setTitle("Distance + Direction + Speed")
        self.dist_dir_group.setGeometry(QRect(570, 640, 400, 140))
        self.dist_dir_group.setObjectName("dist_dir_group")

        QLabel("Direction :", self.dist_dir_group).setGeometry(QRect(10, 28, 80, 25))
        self.dist_dir_combo = QComboBox(self.dist_dir_group)
        self.dist_dir_combo.setObjectName("dist_dir_combo")
        self.dist_dir_combo.setGeometry(QRect(95, 28, 165, 25))
        for _lbl in ["전진 (Forward)", "후진 (Backward)",
                     "좌측 (Left)", "우측 (Right)",
                     "대각 전좌 (FrontLeft)", "대각 전우 (FrontRight)",
                     "대각 후좌 (BackLeft)", "대각 후우 (BackRight)",
                     "좌회전 (RotateL)", "우회전 (RotateR)"]:
            self.dist_dir_combo.addItem(_lbl)

        QLabel("Distance (cm) :", self.dist_dir_group).setGeometry(QRect(10, 62, 100, 25))
        self.dist_dir_cm_spin = QDoubleSpinBox(self.dist_dir_group)
        self.dist_dir_cm_spin.setObjectName("dist_dir_cm_spin")
        self.dist_dir_cm_spin.setGeometry(QRect(115, 62, 120, 25))
        self.dist_dir_cm_spin.setRange(1.0, 500.0)
        self.dist_dir_cm_spin.setSingleStep(1.0)
        self.dist_dir_cm_spin.setDecimals(1)
        self.dist_dir_cm_spin.setValue(30.0)
        self.dist_dir_cm_spin.setSuffix(" cm")

        QLabel("Speed :", self.dist_dir_group).setGeometry(QRect(10, 96, 100, 25))
        self.dist_dir_speed_spin = QSpinBox(self.dist_dir_group)
        self.dist_dir_speed_spin.setObjectName("dist_dir_speed_spin")
        self.dist_dir_speed_spin.setGeometry(QRect(115, 96, 120, 25))
        self.dist_dir_speed_spin.setRange(0, 255)
        self.dist_dir_speed_spin.setValue(150)
        self.dist_dir_speed_spin.setSuffix("  (0~255)")

        self.dist_dir_run_btn = QPushButton("▶ Run", self.dist_dir_group)
        self.dist_dir_run_btn.setObjectName("dist_dir_run_btn")
        self.dist_dir_run_btn.setGeometry(QRect(248, 55, 142, 70))

        # ── 거리 + 방향 + 시간 제어 패널 ─────────────────────────────────
        self.dist_dir_time_group = QGroupBox(Form)
        self.dist_dir_time_group.setTitle("Distance + Direction + Time")
        self.dist_dir_time_group.setGeometry(QRect(980, 640, 450, 140))
        self.dist_dir_time_group.setObjectName("dist_dir_time_group")

        QLabel("Direction :", self.dist_dir_time_group).setGeometry(QRect(10, 30, 80, 25))
        self.dist_dir_time_dir_combo = QComboBox(self.dist_dir_time_group)
        self.dist_dir_time_dir_combo.setObjectName("dist_dir_time_dir_combo")
        self.dist_dir_time_dir_combo.setGeometry(QRect(95, 30, 175, 25))
        for _lbl in ["전진 (Forward)", "후진 (Backward)",
                     "좌측 (Left)", "우측 (Right)",
                     "대각 전좌 (FrontLeft)", "대각 전우 (FrontRight)",
                     "대각 후좌 (BackLeft)", "대각 후우 (BackRight)",
                     "좌회전 (RotateL)", "우회전 (RotateR)"]:
            self.dist_dir_time_dir_combo.addItem(_lbl)

        QLabel("Dist (cm) :", self.dist_dir_time_group).setGeometry(QRect(10, 65, 75, 25))
        self.dist_dir_time_cm_spin = QDoubleSpinBox(self.dist_dir_time_group)
        self.dist_dir_time_cm_spin.setObjectName("dist_dir_time_cm_spin")
        self.dist_dir_time_cm_spin.setGeometry(QRect(90, 65, 110, 25))
        self.dist_dir_time_cm_spin.setRange(1.0, 500.0)
        self.dist_dir_time_cm_spin.setSingleStep(1.0)
        self.dist_dir_time_cm_spin.setDecimals(1)
        self.dist_dir_time_cm_spin.setValue(30.0)
        self.dist_dir_time_cm_spin.setSuffix(" cm")

        QLabel("Time (s) :", self.dist_dir_time_group).setGeometry(QRect(210, 65, 65, 25))
        self.dist_dir_time_sec_spin = QDoubleSpinBox(self.dist_dir_time_group)
        self.dist_dir_time_sec_spin.setObjectName("dist_dir_time_sec_spin")
        self.dist_dir_time_sec_spin.setGeometry(QRect(278, 65, 90, 25))
        self.dist_dir_time_sec_spin.setRange(0.1, 60.0)
        self.dist_dir_time_sec_spin.setSingleStep(0.1)
        self.dist_dir_time_sec_spin.setDecimals(1)
        self.dist_dir_time_sec_spin.setValue(2.0)
        self.dist_dir_time_sec_spin.setSuffix(" s")

        self.dist_dir_time_run_btn = QPushButton("▶ Run", self.dist_dir_time_group)
        self.dist_dir_time_run_btn.setObjectName("dist_dir_time_run_btn")
        self.dist_dir_time_run_btn.setGeometry(QRect(278, 30, 162, 28))

        # ── 거리 + 방향 + 무게 제어 패널 ─────────────────────────────────────────
        self.dist_dir_weight_group = QGroupBox(Form)
        self.dist_dir_weight_group.setTitle("Distance + Direction + Speed + Weight")
        self.dist_dir_weight_group.setGeometry(QRect(570, 785, 400, 160))
        self.dist_dir_weight_group.setObjectName("dist_dir_weight_group")

        QLabel("Direction :", self.dist_dir_weight_group).setGeometry(QRect(10, 28, 80, 25))
        self.dist_dir_weight_combo = QComboBox(self.dist_dir_weight_group)
        self.dist_dir_weight_combo.setObjectName("dist_dir_weight_combo")
        self.dist_dir_weight_combo.setGeometry(QRect(95, 28, 165, 25))
        for _lbl in ["전진 (Forward)", "후진 (Backward)",
                     "좌측 (Left)", "우측 (Right)",
                     "대각 전좌 (FrontLeft)", "대각 전우 (FrontRight)",
                     "대각 후좌 (BackLeft)", "대각 후우 (BackRight)",
                     "좌회전 (RotateL)", "우회전 (RotateR)"]:
            self.dist_dir_weight_combo.addItem(_lbl)

        QLabel("Distance (cm) :", self.dist_dir_weight_group).setGeometry(QRect(10, 62, 100, 25))
        self.dist_dir_weight_cm_spin = QDoubleSpinBox(self.dist_dir_weight_group)
        self.dist_dir_weight_cm_spin.setObjectName("dist_dir_weight_cm_spin")
        self.dist_dir_weight_cm_spin.setGeometry(QRect(115, 62, 120, 25))
        self.dist_dir_weight_cm_spin.setRange(1.0, 500.0)
        self.dist_dir_weight_cm_spin.setSingleStep(1.0)
        self.dist_dir_weight_cm_spin.setDecimals(1)
        self.dist_dir_weight_cm_spin.setValue(30.0)
        self.dist_dir_weight_cm_spin.setSuffix(" cm")

        QLabel("Speed :", self.dist_dir_weight_group).setGeometry(QRect(10, 96, 100, 25))
        self.dist_dir_weight_speed_spin = QSpinBox(self.dist_dir_weight_group)
        self.dist_dir_weight_speed_spin.setObjectName("dist_dir_weight_speed_spin")
        self.dist_dir_weight_speed_spin.setGeometry(QRect(115, 96, 120, 25))
        self.dist_dir_weight_speed_spin.setRange(0, 255)
        self.dist_dir_weight_speed_spin.setValue(150)
        self.dist_dir_weight_speed_spin.setSuffix("  (0~255)")

        self.dist_dir_weight_run_btn = QPushButton("▶ Run", self.dist_dir_weight_group)
        self.dist_dir_weight_run_btn.setObjectName("dist_dir_weight_run_btn")
        self.dist_dir_weight_run_btn.setGeometry(QRect(248, 55, 142, 70))

        QLabel("Weight (g) :", self.dist_dir_weight_group).setGeometry(QRect(10, 130, 100, 25))
        self.dist_dir_weight_g_spin = QDoubleSpinBox(self.dist_dir_weight_group)
        self.dist_dir_weight_g_spin.setObjectName("dist_dir_weight_g_spin")
        self.dist_dir_weight_g_spin.setGeometry(QRect(115, 130, 120, 25))
        self.dist_dir_weight_g_spin.setRange(50.0, 10000.0)
        self.dist_dir_weight_g_spin.setSingleStep(1.0)
        self.dist_dir_weight_g_spin.setDecimals(1)
        self.dist_dir_weight_g_spin.setValue(30.0)
        self.dist_dir_weight_g_spin.setSuffix(" g")

        # ── 거리 + 방향 + 시간 + 무게 제어 패널 ─────────────────────────────────
        self.dist_dir_time_weight_group = QGroupBox(Form)
        self.dist_dir_time_weight_group.setTitle("Distance + Direction + Time + Weight")
        self.dist_dir_time_weight_group.setGeometry(QRect(980, 785, 450, 160))
        self.dist_dir_time_weight_group.setObjectName("dist_dir_time_weight_group")

        QLabel("Direction :", self.dist_dir_time_weight_group).setGeometry(QRect(10, 30, 80, 25))
        self.dist_dir_time_weight_dir_combo = QComboBox(self.dist_dir_time_weight_group)
        self.dist_dir_time_weight_dir_combo.setObjectName("dist_dir_time_weight_dir_combo")
        self.dist_dir_time_weight_dir_combo.setGeometry(QRect(95, 30, 175, 25))
        for _lbl in ["전진 (Forward)", "후진 (Backward)",
                     "좌측 (Left)", "우측 (Right)",
                     "대각 전좌 (FrontLeft)", "대각 전우 (FrontRight)",
                     "대각 후좌 (BackLeft)", "대각 후우 (BackRight)",
                     "좌회전 (RotateL)", "우회전 (RotateR)"]:
            self.dist_dir_time_weight_dir_combo.addItem(_lbl)

        QLabel("Dist (cm) :", self.dist_dir_time_weight_group).setGeometry(QRect(10, 65, 75, 25))
        self.dist_dir_time_weight_cm_spin = QDoubleSpinBox(self.dist_dir_time_weight_group)
        self.dist_dir_time_weight_cm_spin.setObjectName("dist_dir_time_weight_cm_spin")
        self.dist_dir_time_weight_cm_spin.setGeometry(QRect(90, 65, 110, 25))
        self.dist_dir_time_weight_cm_spin.setRange(1.0, 500.0)
        self.dist_dir_time_weight_cm_spin.setSingleStep(1.0)
        self.dist_dir_time_weight_cm_spin.setDecimals(1)
        self.dist_dir_time_weight_cm_spin.setValue(30.0)
        self.dist_dir_time_weight_cm_spin.setSuffix(" cm")

        QLabel("Time (s) :", self.dist_dir_time_weight_group).setGeometry(QRect(210, 65, 65, 25))
        self.dist_dir_time_weight_sec_spin = QDoubleSpinBox(self.dist_dir_time_weight_group)
        self.dist_dir_time_weight_sec_spin.setObjectName("dist_dir_time_weight_sec_spin")
        self.dist_dir_time_weight_sec_spin.setGeometry(QRect(278, 65, 90, 25))
        self.dist_dir_time_weight_sec_spin.setRange(0.1, 60.0)
        self.dist_dir_time_weight_sec_spin.setSingleStep(0.1)
        self.dist_dir_time_weight_sec_spin.setDecimals(1)
        self.dist_dir_time_weight_sec_spin.setValue(2.0)
        self.dist_dir_time_weight_sec_spin.setSuffix(" s")

        self.dist_dir_time_weight_run_btn = QPushButton("▶ Run", self.dist_dir_time_weight_group)
        self.dist_dir_time_weight_run_btn.setObjectName("dist_dir_time_weight_run_btn")
        self.dist_dir_time_weight_run_btn.setGeometry(QRect(278, 30, 162, 28))

        QLabel("Weight (g) :", self.dist_dir_time_weight_group).setGeometry(QRect(10, 100, 75, 25))
        self.dist_dir_time_weight_g_spin = QDoubleSpinBox(self.dist_dir_time_weight_group)
        self.dist_dir_time_weight_g_spin.setObjectName("dist_dir_time_weight_sec_spin")
        self.dist_dir_time_weight_g_spin.setGeometry(QRect(95, 100, 90, 25))
        self.dist_dir_time_weight_g_spin.setRange(50.0, 10000.0)
        self.dist_dir_time_weight_g_spin.setSingleStep(1.0)
        self.dist_dir_time_weight_g_spin.setDecimals(1)
        self.dist_dir_time_weight_g_spin.setValue(50.0)
        self.dist_dir_time_weight_g_spin.setSuffix(" g")

        # ── 비상정지 버튼 (빨간색) ─────────────────────────────────────────
        self.emg_stop_btn = QPushButton("⛔ STOP", Form)
        self.emg_stop_btn.setObjectName("emg_stop_btn")
        self.emg_stop_btn.setGeometry(QRect(1180, 545, 250, 95))
        self.emg_stop_btn.setStyleSheet(
            "QPushButton {"
            "  background-color: #cc0000;"
            "  color: white;"
            "  font-size: 18px;"
            "  font-weight: bold;"
            "  border-radius: 8px;"
            "  border: 3px solid #880000;"
            "}"
            "QPushButton:pressed {"
            "  background-color: #880000;"
            "}"
            "QPushButton:hover {"
            "  background-color: #ee1111;"
            "}"
        )

        # ── CSV 경로 제어 패널 ────────────────────────────────────────────
        self.csv_group = QGroupBox(Form)
        self.csv_group.setTitle("CSV Path Control")
        self.csv_group.setGeometry(QRect(10, 805, 550, 185))
        self.csv_group.setObjectName("csv_group")

        # 행1: 파일 경로 표시 + 불러오기 + 새 파일 만들기
        QLabel("파일 :", self.csv_group).setGeometry(QRect(10, 28, 40, 25))
        QLabel("파일 :", self.csv_group).setGeometry(QRect(10, 28, 40, 25))
        self.csv_path_edit = QLineEdit(self.csv_group)
        self.csv_path_edit.setObjectName("csv_path_edit")
        self.csv_path_edit.setGeometry(QRect(55, 28, 350, 25))
        self.csv_path_edit.setReadOnly(True)
        self.csv_path_edit.setPlaceholderText("CSV 파일을 불러오거나 새로 만드세요")

        self.csv_load_btn = QPushButton("📂 불러오기", self.csv_group)
        self.csv_load_btn.setObjectName("csv_load_btn")
        self.csv_load_btn.setGeometry(QRect(410, 25, 80, 30))

        self.csv_new_btn = QPushButton("📝 새 파일 만들기", self.csv_group)
        self.csv_new_btn.setObjectName("csv_new_btn")
        self.csv_new_btn.setGeometry(QRect(410, 60, 110, 30))

        # 행2: 새 파일명 입력 (새 파일 만들기 전용)
        QLabel("새 파일명 :", self.csv_group).setGeometry(QRect(10, 65, 70, 25))
        self.csv_new_name_edit = QLineEdit(self.csv_group)
        self.csv_new_name_edit.setObjectName("csv_new_name_edit")
        self.csv_new_name_edit.setGeometry(QRect(85, 65, 200, 25))
        self.csv_new_name_edit.setPlaceholderText("route_001  (확장자 없이 입력)")

        self.csv_total_label = QLabel("총 스탭: -", self.csv_group)
        self.csv_total_label.setObjectName("csv_total_label")
        self.csv_total_label.setGeometry(QRect(300, 65, 200, 25))

        # 행3: 현재 스탭 진행 상태 + 실행 버튼
        self.csv_step_label = QLabel("대기 중", self.csv_group)
        self.csv_step_label.setObjectName("csv_step_label")
        self.csv_step_label.setGeometry(QRect(10, 100, 525, 35))
        self.csv_step_label.setAlignment(Qt.AlignmentFlag.AlignVCenter | Qt.AlignmentFlag.AlignLeft)
        self.csv_step_label.setStyleSheet(
            "font-size: 15px; font-weight: bold; color: #222; "
            "background: #f0f0f0; border: 1px solid #ccc; border-radius: 4px; "
            "padding-left: 8px;"
        )

        self.csv_run_btn = QPushButton("▶ 실행", self.csv_group)
        self.csv_run_btn.setObjectName("csv_run_btn")
        self.csv_run_btn.setGeometry(QRect(330, 140, 200, 38))

        # ── IMU 그룹박스 (오른쪽 하단) ─────────────────────────────────────────
        self.imu_group = QGroupBox("IMU (MPU-6050)", Form)
        self.imu_group.setGeometry(QRect(10, 620, 550, 180))
        self.imu_group.setStyleSheet("""
            QGroupBox {
                border: 1px solid #ccc;
                border-radius: 6px;
                margin-top: 10px;
                background-color: #fcfcfc;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 10px;
                padding: 0 5px 0 5px;
                color: #333;
            }
        """)

        # 공통 위치 상수 (2열 구조)
        _H_ROW = 25
        _Y_ACC = 20
        _Y_GYR = 50
        _Y_MAG = 80    # Mag 행
        _Y_RPY = 110   # Roll / Pitch / Yaw 행
        # Roll: X열, Pitch: Y열, Yaw: Z열 재활용
        
        _X_TITLE = 10
        _W_TITLE = 60
        
        _X_LBL_X = 100; _X_VAL_X = 140
        _X_LBL_Y = 240; _X_VAL_Y = 280
        _X_LBL_Z = 380; _X_VAL_Z = 420
        
        _W_TAG = 30
        _W_VAL = 60

        _ALIGN_R = Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter
        _VAL_STYLE = ("color: #0044cc; font-weight: bold; background: #eee;"
                      " border-radius: 4px; padding-right: 5px;")

        # ── Accel 행 ────────────────────────────────────────────────────────
        _lbl_acc = QLabel("Accel (g)", self.imu_group)
        _lbl_acc.setGeometry(QRect(_X_TITLE, _Y_ACC, _W_TITLE, _H_ROW))

        _lbl_ax = QLabel("X:", self.imu_group)
        _lbl_ax.setAlignment(_ALIGN_R)
        _lbl_ax.setGeometry(QRect(_X_LBL_X, _Y_ACC, _W_TAG, _H_ROW))

        self.imu_lbl_ax = QLabel("--", self.imu_group)
        self.imu_lbl_ax.setObjectName("imu_lbl_ax")
        self.imu_lbl_ax.setGeometry(QRect(_X_VAL_X, _Y_ACC, _W_VAL, _H_ROW))
        self.imu_lbl_ax.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_ax.setAlignment(_ALIGN_R)

        _lbl_ay = QLabel("Y:", self.imu_group)
        _lbl_ay.setAlignment(_ALIGN_R)
        _lbl_ay.setGeometry(QRect(_X_LBL_Y, _Y_ACC, _W_TAG, _H_ROW))

        self.imu_lbl_ay = QLabel("--", self.imu_group)
        self.imu_lbl_ay.setObjectName("imu_lbl_ay")
        self.imu_lbl_ay.setGeometry(QRect(_X_VAL_Y, _Y_ACC, _W_VAL, _H_ROW))
        self.imu_lbl_ay.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_ay.setAlignment(_ALIGN_R)

        _lbl_az = QLabel("Z:", self.imu_group)
        _lbl_az.setAlignment(_ALIGN_R)
        _lbl_az.setGeometry(QRect(_X_LBL_Z, _Y_ACC, _W_TAG, _H_ROW))

        self.imu_lbl_az = QLabel("--", self.imu_group)
        self.imu_lbl_az.setObjectName("imu_lbl_az")
        self.imu_lbl_az.setGeometry(QRect(_X_VAL_Z, _Y_ACC, _W_VAL, _H_ROW))
        self.imu_lbl_az.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_az.setAlignment(_ALIGN_R)

        # ── Gyro 행 ─────────────────────────────────────────────────────────
        _lbl_gyr = QLabel("Gyro (°/s)", self.imu_group)
        _lbl_gyr.setGeometry(QRect(_X_TITLE, _Y_GYR, _W_TITLE, _H_ROW))

        _lbl_gx = QLabel("X:", self.imu_group)
        _lbl_gx.setAlignment(_ALIGN_R)
        _lbl_gx.setGeometry(QRect(_X_LBL_X, _Y_GYR, _W_TAG, _H_ROW))

        self.imu_lbl_gx = QLabel("--", self.imu_group)
        self.imu_lbl_gx.setObjectName("imu_lbl_gx")
        self.imu_lbl_gx.setGeometry(QRect(_X_VAL_X, _Y_GYR, _W_VAL, _H_ROW))
        self.imu_lbl_gx.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_gx.setAlignment(_ALIGN_R)

        _lbl_gy = QLabel("Y:", self.imu_group)
        _lbl_gy.setAlignment(_ALIGN_R)
        _lbl_gy.setGeometry(QRect(_X_LBL_Y, _Y_GYR, _W_TAG, _H_ROW))

        self.imu_lbl_gy = QLabel("--", self.imu_group)
        self.imu_lbl_gy.setObjectName("imu_lbl_gy")
        self.imu_lbl_gy.setGeometry(QRect(_X_VAL_Y, _Y_GYR, _W_VAL, _H_ROW))
        self.imu_lbl_gy.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_gy.setAlignment(_ALIGN_R)

        _lbl_gz = QLabel("Z:", self.imu_group)
        _lbl_gz.setAlignment(_ALIGN_R)
        _lbl_gz.setGeometry(QRect(_X_LBL_Z, _Y_GYR, _W_TAG, _H_ROW))

        self.imu_lbl_gz = QLabel("--", self.imu_group)
        self.imu_lbl_gz.setObjectName("imu_lbl_gz")
        self.imu_lbl_gz.setGeometry(QRect(_X_VAL_Z, _Y_GYR, _W_VAL, _H_ROW))
        self.imu_lbl_gz.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_gz.setAlignment(_ALIGN_R)

        # ── Mag 행 ──────────────────────────────────────────────────────────
        _lbl_mag = QLabel("Mag (Gs)", self.imu_group)
        _lbl_mag.setGeometry(QRect(_X_TITLE, _Y_MAG, _W_TITLE, _H_ROW))

        _lbl_mx = QLabel("X:", self.imu_group)
        _lbl_mx.setAlignment(_ALIGN_R)
        _lbl_mx.setGeometry(QRect(_X_LBL_X, _Y_MAG, _W_TAG, _H_ROW))

        self.imu_lbl_mx = QLabel("--", self.imu_group)
        self.imu_lbl_mx.setObjectName("imu_lbl_mx")
        self.imu_lbl_mx.setGeometry(QRect(_X_VAL_X, _Y_MAG, _W_VAL, _H_ROW))
        self.imu_lbl_mx.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_mx.setAlignment(_ALIGN_R)

        _lbl_my = QLabel("Y:", self.imu_group)
        _lbl_my.setAlignment(_ALIGN_R)
        _lbl_my.setGeometry(QRect(_X_LBL_Y, _Y_MAG, _W_TAG, _H_ROW))

        self.imu_lbl_my = QLabel("--", self.imu_group)
        self.imu_lbl_my.setObjectName("imu_lbl_my")
        self.imu_lbl_my.setGeometry(QRect(_X_VAL_Y, _Y_MAG, _W_VAL, _H_ROW))
        self.imu_lbl_my.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_my.setAlignment(_ALIGN_R)

        _lbl_mz = QLabel("Z:", self.imu_group)
        _lbl_mz.setAlignment(_ALIGN_R)
        _lbl_mz.setGeometry(QRect(_X_LBL_Z, _Y_MAG, _W_TAG, _H_ROW))

        self.imu_lbl_mz = QLabel("--", self.imu_group)
        self.imu_lbl_mz.setObjectName("imu_lbl_mz")
        self.imu_lbl_mz.setGeometry(QRect(_X_VAL_Z, _Y_MAG, _W_VAL, _H_ROW))
        self.imu_lbl_mz.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_mz.setAlignment(_ALIGN_R)

        # ── Roll / Pitch / Yaw 행 ────────────────────────────────────────────
        # Roll → X열,  Pitch → Y열,  Yaw → Z열  (3열 재사용)
        _lbl_rpy = QLabel("Attitude", self.imu_group)
        _lbl_rpy.setGeometry(QRect(_X_TITLE, _Y_RPY, _W_TITLE, _H_ROW))

        _lbl_roll_tag = QLabel("Roll:", self.imu_group)
        _lbl_roll_tag.setAlignment(_ALIGN_R)
        _lbl_roll_tag.setGeometry(QRect(_X_LBL_X - 20, _Y_RPY, _W_TAG + 20, _H_ROW))

        # Roll/Pitch/Yaw 값 레이블은 ±180.00 같은 긴 텍스트가 들어오므로
        # 별도로 _W_RPY_VAL = 75 사용
        _W_RPY_VAL = 75

        self.imu_lbl_roll = QLabel("--", self.imu_group)
        self.imu_lbl_roll.setObjectName("imu_lbl_roll")
        self.imu_lbl_roll.setGeometry(QRect(_X_VAL_X, _Y_RPY, _W_RPY_VAL, _H_ROW))
        self.imu_lbl_roll.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_roll.setAlignment(_ALIGN_R)

        _lbl_pitch_tag = QLabel("Pitch:", self.imu_group)
        _lbl_pitch_tag.setAlignment(_ALIGN_R)
        _lbl_pitch_tag.setGeometry(QRect(_X_LBL_Y - 20, _Y_RPY, _W_TAG + 20, _H_ROW))

        self.imu_lbl_pitch = QLabel("--", self.imu_group)
        self.imu_lbl_pitch.setObjectName("imu_lbl_pitch")
        self.imu_lbl_pitch.setGeometry(QRect(_X_VAL_Y, _Y_RPY, _W_RPY_VAL, _H_ROW))
        self.imu_lbl_pitch.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_pitch.setAlignment(_ALIGN_R)

        _lbl_yaw_tag = QLabel("Yaw:", self.imu_group)
        _lbl_yaw_tag.setAlignment(_ALIGN_R)
        _lbl_yaw_tag.setGeometry(QRect(_X_LBL_Z - 20, _Y_RPY, _W_TAG + 20, _H_ROW))

        self.imu_lbl_yaw = QLabel("--", self.imu_group)
        self.imu_lbl_yaw.setObjectName("imu_lbl_yaw")
        self.imu_lbl_yaw.setGeometry(QRect(_X_VAL_Z, _Y_RPY, _W_RPY_VAL, _H_ROW))
        self.imu_lbl_yaw.setStyleSheet(_VAL_STYLE)
        self.imu_lbl_yaw.setAlignment(_ALIGN_R)

        # ── 초기화 및 로깅 버튼 ─────────────────────────────────────────────
        self.imu_init_btn = QPushButton("초기화", self.imu_group)
        self.imu_init_btn.setObjectName("imu_init_btn")
        self.imu_init_btn.setGeometry(QRect(10, 140, 60, 30))

        self.imu_log_btn = QPushButton("IMU CSV 로깅 시작", self.imu_group)
        self.imu_log_btn.setObjectName("imu_log_btn")
        self.imu_log_btn.setGeometry(QRect(80, 140, 460, 30))

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

        self.moto_stat_slider.valueChanged.connect(self.motor_speed_slider_valuechange)
        if __name__ != "__main__":
            self.motor_speed_signal.connect(self.motor_speed_update)

    def retranslateUi(self, Form):
        _translate = QApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cam_label.setText(_translate("Form", "Video"))
        self.distance_label.setText(_translate("Form", "10mm"))
        self.moto_btn_frontleft.setText(_translate("Form", "↖ FrontLeft"))
        self.moto_btn_frontright.setText(_translate("Form", "↗ FrontRight"))
        self.moto_btn_front.setText(_translate("Form", "↑ Front"))
        self.moto_btn_left.setText(_translate("Form", "← Left"))
        self.moto_btn_right.setText(_translate("Form", "Right →"))
        self.moto_btn_back.setText(_translate("Form", "Back ↓"))
        self.moto_btn_backleft.setText(_translate("Form", "↙ BackLeft"))
        self.moto_btn_backright.setText(_translate("Form", "↘ BackRight"))
        self.moto_btn_rotate_right.setText(_translate("Form", "Rotate_Right"))
        self.moto_btn_rotate_left.setText(_translate("Form", "Rotate_Left"))
        self.robot_ip_label.setText(_translate("Form", "Robot IP :"))
        self.pushButton.setText(_translate("Form", "Connect"))
        self.groupBox.setTitle(_translate("Form", "RGB_Bar"))
        self.pushButton_2.setText(_translate("Form", "OFF"))
        self.pushButton_3.setText(_translate("Form", "RED"))
        self.pushButton_4.setText(_translate("Form", "GREEN"))
        self.pushButton_5.setText(_translate("Form", "BLUE"))
        self.pushButton_6.setText(_translate("Form", "YELLOW"))
        self.pushButton_7.setText(_translate("Form", "PURPLE"))
        self.pushButton_8.setText(_translate("Form", "CYAN"))
        self.pushButton_9.setText(_translate("Form", "WHITE"))
        self.label.setText(_translate("Form", "Color : RBG(10,10.10)"))
        self.pushButton_10.setText(_translate("Form", "Change"))
        self.label_2.setText(_translate("Form", "Red : "))
        self.label_3.setText(_translate("Form", "Green : "))
        self.label_4.setText(_translate("Form", "Blue : "))
        self.pushButton_11.setText(_translate("Form", "Close"))
        self.moto_stat_label.setText(_translate("Form", f"Power : {self.speed}"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())